djangoproject/blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

djangoproject/djangoproject/templates/410.html
{% extends 'base_error.html' %}

{% block title %}Page removed{% endblock %}

{% block header %}<h1>410</h1>{% endblock %}

{% block content %}
<h2>Page removed.</h2>

<p>Sorry, we've removed some of parts of the site that were completely out
of date. In most cases, that content has been moved into
<a href="{% url 'homepage' host 'docs' %}">the new documentation site</a>.</p>

<p>Here's a link to the <a href="{% url 'homepage' %}">homepage</a>. You know, just in case.</p>

{% endblock %}

djangoproject/djangoproject/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="{% block html_language_code %}en{% endblock %}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ROBOTS" content="ALL" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="Copyright" content="Django Software Foundation" />
    <meta name="keywords" content="Python, Django, framework, open-source" />
    <meta name="description" content="{% block description %}{% endblock %}" />

    {% block link_rel_tags %}{% endblock link_rel_tags %}
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static "img/icon-touch.png" %}">
    <link rel="icon" sizes="192x192" href="{% static "img/icon-touch.png" %}">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
    <meta name="msapplication-TileColor" content="#113228">
    <meta name="msapplication-TileImage" content="{% static "img/icon-tile.png" %}">

    <title>{% block title %}The web framework for perfectionists with deadlines{% endblock %} | Django</title>

    <link rel="stylesheet" href="{% static "css/output.css" %}" >
    <script src="{% static "js/lib/webfontloader/webfontloader.js" %}"></script>
    <script>
    WebFont.load({
      custom: {
        families: ['FontAwesome', 'Fira+Mono'],
      },
      google: {
        families: ['Roboto:400italic,700italic,300,700,400:latin'
        ]
      },
      classes: false,
      events: false,
      timeout: 1000
    });
    </script>
    <script src="{% static "js/lib/modernizr.js" %}"></script>
    {% block head_extra %}{% endblock head_extra %}
  </head>

  <body id="{% block sectionid %}generic{% endblock %}" class="{% block body_class %}{% endblock %}">

    {% include "includes/header.html" %}

    <div class="copy-banner">
      <div class="container {% block header-classes %}{% endblock %}">
        {% block header %}{% endblock %}
      </div>
    </div>
    <div id="billboard">{% block billboard %}{% endblock %}</div>

    <div class="container {% block layout_class %}{% endblock %}">
      <div role="main">

        {% block messages %}
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  {{ message }}
                  <i class="close icon icon-remove" title="close"></i>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endblock %}

        {% block content %}{% endblock %}
        <a href="#top" class="backtotop"><i class="icon icon-chevron-up"></i> Back to Top</a>
      </div>

      {% block content-related %}{% endblock %}
      {% block content-extra %}{% endblock %}

    </div>

    {% block secondary %}{% endblock %} {# Used only with one column pages: Why Django, Get Started, etc #}
    {% block tertiary %}{% endblock %} {# Used only with one column pages: Why Django, Get Started, etc #}

    {# Used to display urgent news, events, and alerts #}
    {% block alert %}
    {% endblock %}

    {% block footer %}
      {% include "includes/footer.html" %}
    {% endblock %}

    {# Require JS #}
    <script>
    function extless(input) {
        return input.replace(/(.*)\.[^.]+$/, '$1');
    }
    var require = {
        shim: {
            'jquery': [],
            'jquery.inview': ["jquery"],
            'jquery.payment': ["jquery"],
            'jquery.flot': ["jquery"],
            'jquery.unveil': ["jquery"],
            'stripe': {
              exports: 'Stripe'
            }
        },
        paths: {
            "jquery": extless("{% static 'js/lib/jquery/dist/jquery.min.js' %}"),
            "jquery.inview": extless("{% static 'js/lib/jquery.inview/jquery.inview.min.js' %}"),
            "jquery.payment": extless("{% static 'js/lib/jquery.payment/lib/jquery.payment.js' %}"),
            "jquery.unveil": extless("{% static 'js/lib/unveil/jquery.unveil.min.js' %}"),
            "jquery.flot": extless("{% static 'js/lib/jquery-flot/jquery.flot.min.js' %}"),
            "clipboard": extless("{% static 'js/lib/clipboard/dist/clipboard.min.js' %}"),
            "mod/floating-warning": extless("{% static 'js/mod/floating-warning.js' %}"),
            "mod/list-collapsing": extless("{% static 'js/mod/list-collapsing.js' %}"),
            "mod/list-feature": extless("{% static 'js/mod/list-feature.js' %}"),
            "mod/mobile-menu": extless("{% static 'js/mod/mobile-menu.js' %}"),
            "mod/version-switcher": extless("{% static 'js/mod/version-switcher.js' %}"),
            "mod/search-key": extless("{% static 'js/mod/search-key.js' %}"),
            "mod/stripe-change-card": extless("{% static 'js/mod/stripe-change-card.js' %}"),
            "mod/console-tabs": extless("{% static 'js/mod/console-tabs.js' %}"),
            "stripe-checkout": "https://checkout.stripe.com/checkout",
            "stripe": "https://js.stripe.com/v3/?" // ? needed due to require.js
        }
    };
    </script>
    <script data-main="{% static "js/main.js" %}" src="{% static "js/lib/require.js" %}"></script>
    {% block body_extra %}{% endblock body_extra %}

  </body>
</html>

djangoproject/djangoproject/templates/base_2col.html
{% extends "base.html" %}

{% block columnwrap %}
  <div id="content-main">
    {% block content %}
    {% endblock %}
  </div>
  <!-- END #content-main -->
  <div id="content-related" class="sidebar">
    {% block content-related %}
    {% endblock %}
  </div>
  <!-- END #content-related -->
{% endblock %}

djangoproject/djangoproject/templates/base_blogroll.html
{% extends "base_2col" %}

{% block sectionid %}blogroll{% endblock %}

{% block title %}Blogroll{% endblock %}

{% block billboard %}<h2>Blogroll</h2>{% endblock %}

djangoproject/djangoproject/templates/base_code.html
{% extends "base.html" %}

{% block sectionid %}code{% endblock %}

{% block title %}Code{% endblock %}
{% block layout_class %}full-width{% endblock %}

{% block header %}<h1>Django source code</h1>{% endblock %}

djangoproject/djangoproject/templates/base_community.html
{% extends "base.html" %}
{% load fundraising_extras %}

{% block layout_class %}sidebar-right{% endblock %}
{% block title %}Django Community{% endblock %}

{% block header %}
  <h1 class="visuallyhidden">Community</h1>
  <p>Building the <em>Django</em> Community{% if community_stats %}
  {% if community_stats.age %} for <em>{{ community_stats.age }}</em>{% endif %}{% endif %}. Come join us!</p>
{% endblock %}

{% block content-related %}
<h1 class="visuallyhidden">Additional Information</h1>
<div role="complementary">
  {% donation_snippet %}

  <h2>Get Involved</h2>
  <dl class="list-links">
    <dt><a href="https://code.djangoproject.com/">Ticket system</a></dt>
    <dd>report bugs and make feature requests</dd>
    <dt><a href="https://dashboard.djangoproject.com/">Development dashboard</a></dt>
    <dd>see what's currently being worked on</dd>
  </dl>
  <h2>Get Help</h2>
  <dl class="list-links">
    <dt><a href="{% url 'document-detail' lang='en' version='stable' url='faq' host 'docs' %}">Check our FAQ first.</a></dt>
    <dd>Try the FAQ — it's got answers to many common questions.</dd>
    <dt><a href="irc://irc.libera.chat/django">#django IRC channel</a></dt>
    <dd>chat with other Django users</dd>
    <dt><a href="https://discord.gg/xcRH6mN4fa" target="_blank">Django Discord Server</a></dt>
    <dd>Join the Django Discord Community</dd>
    <dt><a href="https://forum.djangoproject.com/" target="_blank">Official Django Forum</a></dt>
    <dd>Join the community on the Django Forum.</dd>
  </dl>

  <h2>Tell the World</h2>
  <dl class="list-links">
    <dt><a href="https://www.djangopackages.com/">Django-based packages</a></dt>
    <dd>find Django based projects and packages</dd>
    <dt><a href="https://www.djangosites.org/">Django-powered sites</a></dt>
    <dd>add your site to the list</dd>
    <dt><a href="/community/badges/">Django badges</a></dt>
    <dd>show your support (or wish longingly)</dd>
    <dt><a href="/community/logos/">Django logos </a></dt>
    <dd>download official logos</dd>
    <dt><a href="/community/desktops/">Django wallpaper</a></dt>
    <dd>cover your desktop</dd>
  </dl>
  <h2>Improve Django</h2>
  <dl class="list-links">
    <dt><a href="https://groups.google.com/group/django-updates">django-updates mailing list</a></dt>
    <dd>get updated for each code and ticket change (for the super-obsessed)</dd>
    <dt><a href="https://code.djangoproject.com/wiki">Django wiki</a></dt>
    <dd>contribute tips and documentation</dd>
  </dl>
</div>
{% endblock %}

djangoproject/djangoproject/templates/base_error.html
{% extends "base_community.html" %}

djangoproject/djangoproject/templates/base_foundation.html
{% extends "base.html" %}
{% load fundraising_extras %}

{% block layout_class %}sidebar-right{% endblock %}
{% block title %}Django Software Foundation{% endblock %}

{% block header %}
  <h1>Django Software Foundation</h1>
{% endblock %}

{% block content-related %}

{# Always include <h1> label and <div> with aria role. #}
<h1 class="visuallyhidden">Additional Information</h1>
<div role="complementary">
  {% donation_snippet %}

  <h2>About the foundation</h2>
  <ul class="list-links">
    <li><a href="/foundation/faq/">FAQ</a></li>
    <li><a href="/foundation/records/">Records</a></li>
    <li><a href="{% url 'contact_foundation' %}">Contact us</a></li>
    <li><a href="/foundation/cla/">Contributor license agreements</a></li>
    <li><a href="/foundation/conferences/">Organizing a Django conference</a></li>
  </ul>
</div>
{% endblock %}

djangoproject/djangoproject/templates/base_weblog.html
{% extends "base.html" %}
{% load weblog fundraising_extras %}
{% block layout_class %}sidebar-right{% endblock %}
{% block title %}News &amp; Events{% endblock %}

{% block header %}
  <h1><a href="{% url 'weblog:index' %}">News &amp; Events</a></h1>
{% endblock %}

{% block head_extra %}
  <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url 'weblog-feed' %}" />
{% endblock %}

{% block content-related %}
  <h1 class="visuallyhidden">Additional Information</h1>
  <div role="complementary">
    {% donation_snippet %}

    {% if events %}
    <h2>Upcoming Events</h2>
    <ul class="list-events">
      {% for event in events %}
        <li>
          <a href="{{ event.external_url }}" target="_blank">{{ event.headline }}</a>
          <span class="meta"><span>{{ event.date|date:"F j, Y" }}</span>  |  {{ event.location }}</span>
          <i class="icon icon-calendar"></i>
        </li>
      {% endfor %}
    </ul>
    {% endif %}
    <p><a href="/foundation/conferences/">Want your event listed here?</a></p>

    {% comment %}
    {# tags not implemented in backend yet #}
    <h2><span>Tags</span></h2>
    <ul class="list-tags">
      <li><a href="#">Django Software Foundation</a></li>
      <li><a href="#">Events</a></li>
      <li><a href="#">Conferences</a></li>
      <li><a href="#">Release Announcements</a></li>
      <li><a href="#">Security</a></li>
    </ul>
    {% endcomment %}

    <h2><span>Archives</span></h2>
    {% render_month_links %}

    <h2><span>RSS Feeds</span></h2>
    <ul class="list-links-small rss-list">
      <li><a href="{% url 'weblog-feed' %}">Latest news entries</a></li>
      <li><a href="https://code.djangoproject.com/timeline?daysback=90&max=50&wiki=on&ticket=on&changeset=on&milestone=on&format=rss">Recent code changes</a></li>
    </ul>
</div>
{% endblock %}

djangoproject/djangoproject/templates/donate_thanks.html
{% extends "flatpages/foundation.html" %}

{% block title %}Thanks for your support!{% endblock %}

{% block content %}
  <h1>Thanks for your support!</h1>
  <h2 class="deck">Thank you for supporting Django. If you like, you can use one of the badges below to show your support and help us bring in other donors.</h2>

  <p>Copy and paste the source below each image to link to our donation page.</p>

  <h3><a href="https://www.djangoproject.com/foundation/donate/"><img src="https://www.djangoproject.com/s/img/badges/djangodonated126x54.gif" border="0" alt="I donated to Django" width="126" height="54" /></a></h3>

  <p><textarea rows="3" cols="60" class="codedump"><a href="https://www.djangoproject.com/foundation/donate/"><img src="https://www.djangoproject.com/s/img/badges/djangodonated126x54.gif" border="0" alt="I donated to Django" width="126" height="54" /></a></textarea><br /><strong>126x54</strong> I donated to Django (green)</p>

  <h3><a href="https://www.djangoproject.com/foundation/donate/"><img src="https://www.djangoproject.com/s/img/badges/djangodonated126x54_grey.png" border="0" alt="I donated to Django" width="126" height="54" /></a></h3>

  <p><textarea rows="3" cols="60" class="codedump"><a href="https://www.djangoproject.com/foundation/donate/"><img src="https://www.djangoproject.com/s/img/badges/djangodonated126x54_grey.png" border="0" alt="I donated to Django" width="126" height="54" /></a></textarea><br /><strong>126x54</strong> I donated to Django (grey)</p>
{% endblock %}

djangoproject/djangoproject/templates/homepage.html
{% extends "base_3col.html" %}
{% load weblog fundraising_extras %}

{% block sectionid %}homepage{% endblock %}
{% block body_class %}homepage{% endblock %}
{% block layout_class %}sidebar-right{% endblock %}

{% block header %}
  <h1 class="visuallyhidden">Django</h1>
    <p>
        <em>Django makes it easier to build better web apps more quickly and with less code.</em>
    </p>
    <p>
        <a href="{% url 'start' %}" class="cta">Get started with Django</a>
    </p>
{% endblock %}

{% block content %}
    <div class="section">
        <h1>Meet Django</h1>
        <p>
          Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.
          Built by experienced developers, it takes care of much of the hassle of web development, so you can focus
          on writing your app without needing to reinvent the wheel. It’s free and open source.
        </p>
        <dl class="list-features">
          <dt><i class="icon icon-bolt"></i> Ridiculously fast.</dt>
          <dd>
            <p>Django was designed to help developers take applications from concept to completion as quickly as possible.</p>
          </dd>

          <dt><i class="icon icon-lock"></i> Reassuringly secure.</dt>
          <dd>
            <p>Django takes security seriously and helps developers avoid many common security mistakes.</p>
          </dd>

          <dt><i class="icon icon-dashboard"></i> Exceedingly scalable.</dt>
          <dd>
            <p>Some of the busiest sites on the web leverage Django’s ability to quickly and flexibly scale.</p>
          </dd>
        </dl>

        <a href="{% url 'overview' %}" class="cta outline">Learn more about Django</a>
    </div>

    {% comment %}

    <div class="section">
        <h1>Who is Django for?</h1>

        <p>
          You’ve probably used a site that uses Django. Find out why Django was the right solution for these organizations, and why you should start building your project with Django today.
        </p>

        <ul class="list-case-study">
          <li>
            <h3 class="logo" title="Mozilla">Mozilla</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
            <a href="{% url 'case_study' %}">Read Case Study</a>
          </li>
          <li>
            <h3 class="logo" title="Disqus">Disqus</h3>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <a href="{% url 'case_study' %}">Read Case Study</a>
          </li>
          <li>
            <h3 class="logo" title="Knight Foundation">Knight Foundation</h3>
            <p>When the Knight Foundation began redesigning their <a href="https://www.knightfoundation.org">site</a>, they were on multiple content management systems they’d outgrown, with a site that couldn’t handle traffic spikes. Knight needed a future-proof solution.</p>
            <a href="{% url 'case_study' %}">Read Case Study</a>
          </li>
        </ul>

        <a href="{% url 'case_study_index' %}" class="cta outline">See all case studies</a>

    </div>

    {% endcomment %}

    <div class="section">
    <h1>Stay in the loop</h1>
    <p>Subscribe to one of our mailing lists to stay up to date with everything in the Django community:</p>
    {% include "includes/mailing_lists.html" %}
    </div>

    <!-- END #content-secondary -->
{% endblock %}

{% block content-related %}
  <div role="complementary">
      <a href="{% url 'download' %}" class="cta">
          Download <em>latest release: {{ DJANGO_VERSION }}</em>
      </a>
      <a href="{% block doc_url %}{% url 'homepage' host 'docs' %}{% endblock %}" class="link-readmore">Django documentation</a>

      {% donation_snippet %}

      <h3>Latest news</h3>
      {% render_latest_blog_entries 2 hide_readmore=True summary_first=True header_tag='h4' %}
      <a href="{% url 'weblog:index' %}" class="link-readmore">More news</a>

      <h3>New to Django?</h3>
      <ul class="list-links-small docs-list">
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='intro/install' host 'docs' %}">Installation guide</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='intro/tutorial01' host 'docs' %}">Write your first Django app</a></li>
      </ul>
      <a href="{% url 'start' %}" class="link-readmore">Getting started with Django</a>

      <h3>The power of Django</h3>
      <ul class="list-links-small docs-list">
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='topics/db/models' host 'docs' %}">Object-relational mapper</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='intro/tutorial02' host 'docs' %}">Automatic admin interface</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='topics/templates' host 'docs' %}">Robust template system</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='stable' url='topics/i18n' host 'docs' %}">Quick internationalization</a></li>
      </ul>
      <a href="{% url 'overview' %}" class="link-readmore">Explore more features</a>

      <h3>Get involved</h3>
      <dl class="list-links-small">
          <dt><a href="https://code.djangoproject.com/">Ticket system</a></dt>
          <dd>
            Report bugs and make feature requests
          </dd>
          <dt><a href="https://dashboard.djangoproject.com/">Development dashboard</a></dt>
          <dd>
            see what's currently being worked on
          </dd>
      </dl>
      <a href="{% url 'community-index' %}" class="link-readmore">Inside the Django community</a>
      
      <h3>Get Help</h3>
      <dl class="list-links-small">
         <dt><a href="irc://irc.libera.chat/django">#django IRC channel</a></dt>
          <dd>
            Chat with other Django users
          </dd>

          <dt><a href="https://discord.gg/xcRH6mN4fa" target="_blank">Django Discord Server</a></dt>
          <dd>
            Join the Django Discord Community
          </dd>

          <dt><a href="https://forum.djangoproject.com/" target="_blank">Official Django Forum</a></dt>
          <dd>
            Join the community on the Django Forum.
          </dd>
      </dl>

      <h3>The Django Software Foundation</h3>
      <dl class="list-links-small">
        <dt><a href="/foundation/">About the Foundation</a></dt>
        <dd>
          Our non-profit supports the project
        </dd>

        <dt><a href="/foundation/donate/">Support Django</a></dt>
        <dd>
          Your contribution makes Django stronger
        </dd>

        <dt><a href="/contact/foundation/">Contact the Django Software Foundation</a></dt>
        <dd></dd>
      </dl>
      <a href="/foundation/" class="link-readmore">More about the DSF</a>
      {% comment %}
      <h3>Upcoming Events</h3>
      <dl class="list-links-small news-list">
        <dt class="event"><a href="#">DjangoCon 2013 Call for Papers</a></dt>
        <dd>
          April 7th, 2013 | Berlin, Germany
        </dd>

        <dt class="event"><a href="#">DjangoCon 2013 Call for Papers</a></dt>
        <dd>April 7th, 2013 | Berlin, Germany</dd>
      </dl>
      <a href="{% url 'weblog:index' %}" class="link-readmore">See all Events</a>
      {% endcomment %}
  </div>

{% endblock %}

{% block alert %}
  {% comment %}
  <div role="alert">
    <div class="container">
      <dl>
        <dt>
          <i class="icon icon-bullhorn"></i>
          <a href="#">Django Fundraising Drive 2014</a>
        </dt>
        <dd>
          The quickest &amp; most fun way to support Django.
          <a href="#" class="link-readmore">Learn more</a>
        </dd>
      </dl>
    </div>
  </div>
  {% endcomment %}
{% endblock %}

djangoproject/djangoproject/templates/overview.html
{% extends 'base.html' %}

{% block title %}Django overview{% endblock %}
{% block layout_class %}full-width{% endblock %}

{% block header %}
  <h1 class="visuallyhidden">Django Overview</h1>
  <p><em>Django</em> was invented to meet fast-moving <em>newsroom deadlines</em>, while satisfying the tough requirements of <em>experienced web developers</em>.</p>
{% endblock %}

{% block content %}
  <h1>Why Django?</h1>

  <p>With Django, you can take web applications from concept to launch in a matter of hours. Django takes care of much of the hassle of web development, so you can focus
     on writing your app without needing to reinvent the wheel. It’s free and open source.</p>

<dl class="list-features">
  <dt><i class="icon icon-bolt"></i> Ridiculously fast.</dt>
  <dd>
    <p>Django was designed to help developers take applications from concept to completion as quickly as possible.</p>
    <a class="link-readmore" href="{% url 'start' %}">See how fast you can start building</a>
  </dd>

  <dt class="even"><i class="icon icon-briefcase"></i> Fully loaded.</dt>
  <dd class="even">
    <p>Django includes dozens of extras you can use to handle common web development tasks. Django takes care of user authentication, content administration, site maps, RSS feeds, and many more tasks — right out of the box.</p>
    <a class="link-readmore" href="{% url 'document-detail' lang='en' version='stable' url='intro/overview' host 'docs' %}">See what’s included</a>
  </dd>

  <dt><i class="icon icon-lock"></i> Reassuringly secure.</dt>
  <dd>
    <p>Django takes security seriously and helps developers avoid many common security mistakes, such as SQL injection, cross-site scripting, cross-site request forgery and clickjacking. Its user authentication system provides a secure way to manage user accounts and passwords.</p>
    <a class="link-readmore" href="{% url 'document-detail' lang='en' version='stable' url='topics/security' host 'docs' %}">Read our security overview</a>
  </dd>

  <dt class="even"><i class="icon icon-dashboard"></i> Exceedingly scalable.</dt>
  <dd class="even">
    <p>Some of the busiest sites on the planet use Django’s ability to quickly and flexibly scale to meet the heaviest traffic demands.</p>
    <a class="link-readmore" href="{% url 'document-detail' lang='en' version='stable' url='faq/general' host 'docs' %}#does-django-scale">Learn more about scaling Django applications</a>
  </dd>

  <dt><i class="icon icon-cogs"></i> Incredibly versatile.</dt>
  <dd>
    <p>Companies, organizations and governments have used Django to build all sorts of things — from content management systems to social networks to scientific computing platforms.</p>
    {% comment %}{# I'm hiding this link until we enable case studies #}<a class="link-readmore" href="#">Call To Action Relating to Feature</a>{% endcomment %}
  </dd>

</dl>

<div class="section">
  <a href="{% url 'start' %}" class="cta">Get started <em>with Django</em></a>
</div>
{% endblock %}

{% block content-related %}

{# Remove the sites in the list below that are used in case studies once they are there #}

{% comment %}
<div class="layout-secondary">
  <div class="container">
    <h1><span>Case Studies</span></h1>
    <p>You’ve probably used a site that uses Django. Find out why Django was the right solution for these organizations.</p>


    <ul class="list-case-study">
      <li>
        <h3 class="logo" title="Mozilla">Mozilla</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
        <a href="{% url 'case_study' %}">Read More</a>
      </li>
      <li>
        <h3 class="logo" title="Disqus">Disqus</h3>
        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="{% url 'case_study' %}">Read More</a>
      </li>
      <li>
        <h3 class="logo" title="Knight Foundation">Knight Foundation</h3>
        <p>When the Knight Foundation began redesigning their <a href="https://www.knightfoundation.org">website</a>, they were on multiple content management systems they’d outgrown, with a site that couldn’t handle traffic spikes. Knight needed a future-proof solution.</p>
        <a href="{% url 'case_study' %}">Read More</a>
      </li>
    </ul>

    <a href="{% url 'case_study_index' %}" class="link-readmore">See all case studies</a>
  </div>
</div>
{% endcomment %}

{% endblock %}

{% block content-extra %}

<div class="layout-tertiary">
  <div class="container">
    <h2>Sites Using Django</h2>
    {# Remove the sites that are used in case studies once they are there #}
    <ul class="list-link-soup">
      <li><a href="https://disqus.com/">Disqus</a></li>
      <li><a href="https://www.instagram.com/">Instagram</a></li>
      <li><a href="https://www.knightfoundation.org/">Knight Foundation</a></li>
      <li><a href="https://www.macfound.org/">MacArthur Foundation</a></li>
      <li><a href="https://www.mozilla.org/">Mozilla</a></li>
      <li><a href="http://www.nationalgeographic.com/">National Geographic</a></li>
      <li><a href="https://okfn.org/">Open Knowledge Foundation</a></li>
      <li><a href="https://www.pinterest.com/">Pinterest</a></li>
      <li><a href="https://www.openstack.org/">Open Stack</a></li>
    </ul>
  </div>
</div>
{% endblock %}