djangoproject/blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

djangoproject/fundraising/urls.py
from django.urls import path

from . import views

app_name = 'fundraising'
urlpatterns = [
    path('', views.index, name='index'),
    path('donation-session', views.configure_checkout_session, name='donation-session'),
    path('thank-you/', views.thank_you, name='thank-you'),
    path('manage-donations/<hero>/', views.manage_donations, name='manage-donations'),
    path('manage-donations/<hero>/cancel/', views.cancel_donation, name='cancel-donation'),
    path('receive-webhook/', views.receive_webhook, name='receive-webhook'),
    path('update-card/', views.update_card, name='update-card'),
]

djangoproject/fundraising/forms.py
import stripe
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django import forms
from django.utils.safestring import mark_safe

from .models import (
    INTERVAL_CHOICES, LEADERSHIP_LEVEL_AMOUNT, DjangoHero, Donation,
)


class DjangoHeroForm(forms.ModelForm):
    hero_type = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        label='I am donating as an',
        choices=DjangoHero.HERO_TYPE_CHOICES,
        initial=DjangoHero.HERO_TYPE_CHOICES[0][0],
    )
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'required',
                'placeholder': 'Your name or the name of your organization',
            },
        )
    )
    location = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Where are you located? (optional; will not be displayed)',
            },
        )
    )
    url = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Which URL should we link your name to?',
            },
        )
    )
    logo = forms.FileField(
        required=False,
        help_text=(
            "If you've donated at least US $%d, you can submit your logo and "
            "we will display it, too." % LEADERSHIP_LEVEL_AMOUNT
        ),
    )
    is_visible = forms.BooleanField(
        required=False,
        label=(
            "Yes, display my name, URL, and logo on this site. "
            "It'll be displayed shortly after we verify it."
        ),
    )
    is_subscribed = forms.BooleanField(
        required=False,
        label=(
            'Yes, the Django Software Foundation can inform me about '
            'future fundraising campaigns by email.'
        ),
    )

    class Meta:
        model = DjangoHero
        fields = (
            'hero_type', 'name', 'location', 'url', 'logo', 'is_visible',
            'is_subscribed',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.checkbox_fields = []
        self.radio_select_fields = []

        for name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput):
                self.checkbox_fields.append(name)
            elif isinstance(field.widget, forms.RadioSelect):
                self.radio_select_fields.append(name)

    def save(self, commit=True):
        hero = super().save(commit=commit)
        customer = stripe.Customer.retrieve(hero.stripe_customer_id)
        customer.description = hero.name or None
        customer.email = hero.email or None
        customer.save()
        return hero


class StripeTextInput(forms.TextInput):
    """
    Inspired by widgets in django-zebra
    """
    def _add_data_stripe_attr(self, name, kwargs):
        kwargs.setdefault('attrs', {}).update({'data-stripe': name})
        return kwargs

    def _strip_name_attr(self, widget_string, name):
        return widget_string.replace("name=\"%s\"" % (name,), "")

    def render(self, name, *args, **kwargs):
        kwargs = self._add_data_stripe_attr(name, kwargs)
        rendered = super().render(name, *args, **kwargs)
        return mark_safe(self._strip_name_attr(rendered, name))


class DonateForm(forms.Form):
    """
    Used to generate the HTML form in the fundraising page.
    """
    AMOUNT_CHOICES = (
        (25, 'US $25'),
        (50, 'US $50'),
        (100, 'US $100'),
        (250, 'US $250'),
        (500, 'US $500'),
        (750, 'US $750'),
        (1000, 'US $1,000'),
        (1250, 'US $1,250'),
        (2500, 'US $2,500'),
        ('custom', 'Other amount'),
    )

    amount = forms.ChoiceField(choices=AMOUNT_CHOICES)
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES)
    captcha = ReCaptchaField(widget=ReCaptchaV3)


class DonationForm(forms.ModelForm):
    """
    Used in the manage donations view.
    """
    subscription_amount = forms.DecimalField(max_digits=9, decimal_places=2, required=True)
    # here we're removing "onetime" option from interval choices:
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES[:3], required=True)

    class Meta:
        model = Donation
        fields = ('subscription_amount', 'interval')

    def save(self, commit=True, *args, **kwargs):
        donation = super().save(commit=commit)
        interval = self.cleaned_data.get('interval')
        amount = self.cleaned_data.get('subscription_amount')

        # Send data to Stripe
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        # TODO: Setting the plan is deprecated — use Price API instead.
        subscription.plan = interval
        subscription.quantity = int(amount)

        subscription.save()

        return donation


class PaymentForm(forms.Form):
    """
    Used to validate values when configuring the Stripe Session.

    `amount` can be any integer, so a ChoiceField is not appropriate.
    """
    captcha = ReCaptchaField(widget=ReCaptchaV3)
    amount = forms.IntegerField(
        required=True,
        min_value=1,  # Minimum payment from Stripe API
        max_value=1_000_000,  # Reject clearly unrealistic amounts.
    )
    interval = forms.ChoiceField(
        required=True,
        choices=INTERVAL_CHOICES,
    )

djangoproject/fundraising/views.py
import decimal
import json
import logging

import stripe
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.forms.models import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import DjangoHeroForm, DonationForm, PaymentForm
from .models import DjangoHero, Donation, Payment, Testimonial

logger = logging.getLogger(__name__)


def index(request):
    testimonial = Testimonial.objects.filter(is_active=True).order_by('?').first()
    return render(request, 'fundraising/index.html', {
        'testimonial': testimonial,
    })


@require_POST
def configure_checkout_session(request):
    """
    Configure the payment session for Stripe.
    Return the Session ID.

    Key attributes are:

    - mode: payment (for one-time charge) or subscription
    - line_items: including price_data because users configure the donation
                  price.

    TODOs

    - Standard amounts could use active Prices, rather than ad-hoc price_data.
    - Tie Stripe customers to site User accounts.
      - If a user is logged in, we can create the session for the correct
        customer.
      - Stripe's documented flows are VERY keen that we create the customer
        first, although the session will do that if we don't.
    - Allow selecting currency. (Smaller task.) Users receive an additional
      charge making payments in foreign currencies. Stripe will convert all
      payments without further charge.
    """

    # Form data:
    # - The interval: which determines the Product and the mode.
    # - The amount: which goes to the Price data.
    form = PaymentForm(request.POST)
    if not form.is_valid():
        data = {
            'success': False,
            'error': form.errors
        }
        return JsonResponse(data)

    amount = form.cleaned_data["amount"]
    interval = form.cleaned_data["interval"]

    product_details = settings.PRODUCTS[interval]
    is_subscription = product_details.get('recurring', True)

    price_data = {
        'currency': 'usd',
        'unit_amount': amount * 100,
        'product': product_details['product_id']
    }
    if is_subscription:
        price_data['recurring'] = {
            'interval': product_details['interval'],
            "interval_count": product_details["interval_count"],
        }

    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{'price_data': price_data, 'quantity': 1}],
            mode='subscription' if is_subscription else 'payment',
            success_url=request.build_absolute_uri(
                reverse('fundraising:thank-you')
            ),
            cancel_url=request.build_absolute_uri(
                reverse('fundraising:index')
            ),
            # TODO: Drop this when updating API.
            stripe_version="2020-08-27",
        )

        return JsonResponse({'success': True, "sessionId": session["id"]})
    except Exception as e:
        logger.exception('Error configuring Stripe session.')
        return JsonResponse({'success': False, "error": str(e)})


def thank_you(request):
    """
    Generic thank you page. In theory only reached via successful payment, but
    no information is passed from Stripe to be sure.
    """
    return render(request, 'fundraising/thank-you.html', {})


# TODO: Use Stripe's customer portal.
@never_cache
def manage_donations(request, hero):
    hero = get_object_or_404(DjangoHero, pk=hero)
    recurring_donations = hero.donation_set.exclude(stripe_subscription_id='')
    past_payments = Payment.objects.filter(donation__donor=hero).select_related('donation')

    ModifyDonationsFormset = modelformset_factory(Donation, form=DonationForm, extra=0)

    if request.method == 'POST':
        hero_form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=hero,
        )
        modify_donations_formset = ModifyDonationsFormset(
            request.POST,
            queryset=recurring_donations
        )

        if hero_form.is_valid() and modify_donations_formset.is_valid():
            hero_form.save()
            modify_donations_formset.save()
            messages.success(request, "Your information has been updated.")
    else:
        hero_form = DjangoHeroForm(instance=hero)
        modify_donations_formset = ModifyDonationsFormset(
            queryset=recurring_donations
        )

    return render(request, 'fundraising/manage-donations.html', {
        'hero': hero,
        'hero_form': hero_form,
        'modify_donations_formset': modify_donations_formset,
        'recurring_donations': recurring_donations,
        'past_payments': past_payments,
        'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY,
    })


@require_POST
def update_card(request):
    donation = get_object_or_404(Donation, id=request.POST['donation_id'])
    try:
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        subscription.source = request.POST['stripe_token']
        subscription.save()
    except stripe.error.StripeError as e:
        data = {'success': False, 'error': str(e)}
    else:
        data = {'success': True}
    return JsonResponse(data)


@require_POST
def cancel_donation(request, hero):
    donation_id = request.POST.get('donation')
    hero = get_object_or_404(DjangoHero, pk=hero)
    donations = hero.donation_set.exclude(stripe_subscription_id='')
    donation = get_object_or_404(donations, pk=donation_id)

    customer = stripe.Customer.retrieve(donation.stripe_customer_id)
    customer.subscriptions.retrieve(donation.stripe_subscription_id).delete()

    donation.stripe_subscription_id = ''
    donation.save()

    messages.success(request, "Your donation has been canceled.")
    return redirect('fundraising:manage-donations', hero=hero.pk)


@require_POST
@csrf_exempt
def receive_webhook(request):
    try:
        data = json.loads(request.body.decode())
    except ValueError:
        return HttpResponse(422)

    # For security, re-request the event object from Stripe.
    # TODO: Verify shared secret here?
    try:
        event = stripe.Event.retrieve(data['id'])
    except stripe.error.InvalidRequestError:
        return HttpResponse(422)

    return WebhookHandler(event).handle()


class WebhookHandler:
    def __init__(self, event):
        self.event = event

    def handle(self):
        handlers = {
            'invoice.payment_succeeded': self.payment_succeeded,
            'invoice.payment_failed': self.payment_failed,
            'customer.subscription.deleted': self.subscription_cancelled,
            'checkout.session.completed': self.checkout_session_completed,
        }
        handler = handlers.get(self.event.type, lambda: HttpResponse(422))
        return handler()

    def payment_succeeded(self):
        invoice = self.event.data.object
        # Ensure we haven't already processed this payment
        if Payment.objects.filter(stripe_charge_id=invoice.charge).exists():
            # We need a 2xx response otherwise Stripe will keep trying.
            return HttpResponse()
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)
        amount = decimal.Decimal(invoice.total) / 100
        if invoice.charge:
            donation.payment_set.create(amount=amount, stripe_charge_id=invoice.charge)
        return HttpResponse(status=201)

    def subscription_cancelled(self):
        subscription = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=subscription.id)
        donation.stripe_subscription_id = ''
        donation.save()

        mail_text = render_to_string(
            'fundraising/email/subscription_cancelled.txt', {'donation': donation})
        send_mail('Payment cancelled', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def payment_failed(self):
        invoice = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)

        mail_text = render_to_string(
            'fundraising/email/payment_failed.txt', {'donation': donation})
        send_mail('Payment failed', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def get_donation_interval(self, session):
        """
        Helper to determine Donation.interval from completed Stripe Session.
        """
        if session.mode == 'payment':
            return 'onetime'

        # Access the interval via the attached price object.
        # See https://stripe.com/docs/api/subscriptions/object
        # TODO: remove stripe_version when updating account settings.
        subscription = stripe.Subscription.retrieve(session.subscription, stripe_version="2020-08-27")
        recurrance = subscription["items"].data[0].price.recurring
        if recurrance.interval == 'year':
            return 'yearly'
        elif recurrance.interval_count == 3:
            return 'quarterly'
        else:
            return 'monthly'

    def checkout_session_completed(self):
        """
        > Occurs when a Checkout Session has been successfully completed.
        https://stripe.com/docs/api/events/types#event_types-checkout.session.completed
        """
        session = self.event.data.object

djangoproject/djangoproject/templates/fundraising/includes/_form.html
{% for field in form %}
  <div class="form-control">
  {% if field.name in form.checkbox_fields %}
      {{ field }}{{ field.label_tag }}
  {% elif field.name in form.radio_select_fields %}
      {{ field.label }}{{ field }}
  {% else %}
      {{ field }}
  {% endif %}
  {% if field.errors %}<p class="errors">{{ field.errors.as_text }}</p>{% endif %}
  {% if field.help_text %}<p class="footnote">{{ field.help_text }}</p>{% endif %}
  </div>
{% endfor %}

djangoproject/djangoproject/templates/fundraising/includes/_hero_with_logo.html
{% load static thumbnail %}
<div class="hero">
  <div class="hero-logo">
    {% if obj.url %}<a href="{{ obj.url }}" rel="nofollow">{% endif %}
    <img src="{% static 'img/fundraising-heart.svg' %}"
      data-src="{% if obj.logo %}{{ obj.thumbnail.url }}{% else %}{% static 'img/fundraising-heart.svg' %}{% endif %}"
      data-src-retina="{% if obj.logo %}{{ obj.thumbnail.url|resolution:'2x' }}{% else %}{% static 'img/fundraising-heart.svg' %}{% endif %}"
      alt="{{ obj.display_name }}" />
    {% if obj.url %}</a>{% endif %}
  </div>
  <div class="hero-name">
    {% if obj.url %}<a href="{{ obj.url }}" rel="nofollow">{% endif %}{% spaceless %}
    {{ obj.display_name }}
    {% endspaceless %}{% if obj.url %}</a>{% endif %}
    {% if show_description %}{{ obj.description }}{% endif %}
  </div>
</div>

djangoproject/djangoproject/templates/fundraising/includes/display_django_heroes.html
{% load humanize %}
<div class="heroes">
  {% if corporate_members.diamond %}
  <h3>Diamond Corporate Members (${{ corporate_membership_amounts.diamond|intcomma }}+)</h3>
  <p>Our diamond <a href="/foundation/corporate-membership/">corporate
    members</a> include mega corporations and foundations.</p>
  <div>
  {% for obj in corporate_members.diamond %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>
  {% endif %}

  {% if corporate_members.platinum %}
  <h3>Platinum Corporate Members (${{ corporate_membership_amounts.platinum|intcomma }}+)</h3>
  <p>Our platinum <a href="/foundation/corporate-membership/">corporate
    members</a> include organizations of ~500 people.</p>
  <div>
  {% for obj in corporate_members.platinum %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>
  {% endif %}

  {% if corporate_members.gold %}
  <h3>Gold Corporate Members (${{ corporate_membership_amounts.gold|intcomma }}+)</h3>
  <p>Our gold <a href="/foundation/corporate-membership/">corporate
    members</a> include organizations of ~200 people.</p>
  <div>
  {% for obj in corporate_members.gold %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>
  {% endif %}

  {% if corporate_members.silver %}
  <h3>Silver Corporate Members (${{ corporate_membership_amounts.silver|intcomma }}+)</h3>
  <p>Our silver <a href="/foundation/corporate-membership/">corporate
    members</a> include organizations of ~50 people.</p>
  <div>
  {% for obj in corporate_members.silver %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>
  {% endif %}

  {% if corporate_members.bronze %}
  <h3>Bronze Corporate Members (${{ corporate_membership_amounts.bronze|intcomma }}+)</h3>
  <p>Our bronze <a href="/foundation/corporate-membership/">corporate
    members</a> include organizations of ~10 people.</p>
  <div>
  {% for obj in corporate_members.bronze %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>
  {% endif %}

  <h3><a id="in-kind-donors" href="#in-kind-donors">In-kind donors</a></h3>
  <p>These donors help with significant non-cash contributions.</p>
  <div>
  {% with show_description=True %}
  {% for obj in inkind_donors %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  {% endwith %}
  </div>

  <h3>Leaders (${{ display_logo_amount|intcomma }}+)</h3>
  <p>Leadership-level donors contribute ${{ display_logo_amount|intcomma }} or
    more in a calendar year.</p>
  <div>
  {% for obj in leaders %}
    {% include "fundraising/includes/_hero_with_logo.html" %}
  {% endfor %}
  </div>

  <h3>Heroes</h3>
  <p>Our donor roll for all donations made in the last {{ display_donor_days }} days.</p>
  <div>
  {% for donor in heroes %}
    <div class="no-logo-hero">
      {% if donor.url %}<a href="{{ donor.url }}" rel="nofollow">{% endif %}{% spaceless %}
        <span>{{ donor.name_with_fallback }}</span>
      {% endspaceless %}{% if donor.url %}</a>{% endif %}
    </div>
  {% endfor %}
  </div>
</div>

djangoproject/djangoproject/templates/fundraising/includes/donation_form_with_heart.html
{% load static fundraising_extras humanize %}

{% with goal_percent=donated_amount|as_percentage:goal_amount %}
<div class="fundraising-index" id="donate">

  <div class="fundraising-heart" data-percent="{{ goal_percent }}">
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 503 431">
      <switch>
        <g>
          <g transform="translate(4, 2)" id="pixels">
            <path d="M 71 0 L 213 0 L 213 71 L 284 71 L 284 0 L 426 0 L 426 71 L 497 71 L 497 213 L 426 213 L 426 284 L 355 284 L 355 355 L 284 355 L 284 426 L 213 426 L 213 355 L 142 355 L 142 284 L 71 284 L 71 213 L 0 213 L 0 71 L 71 71 L 71 0" fill="#f8f8f8" stroke="#c0c0c0" stroke-width="1" />
          </g>
          <text x="50%" y="43%" alignment-baseline="middle" text-anchor="middle">{{ goal_percent|floatformat:'0' }}%</text>
        </g>
        <foreignObject>
          <img src="{% static 'img/fundraising-heart.svg' %}" />
        </foreignObject>
      </switch>
    </svg>
  </div>

  <div class="description">
    <ul>
      <li><strong>{{ goal_percent }}% funded</strong></li>
      <li><strong>${{ donated_amount|intcomma }} donated</strong> of US&nbsp;${{ goal_amount|intcomma }} goal for
        {{ goal_start_date|date:"Y" }}</li>
      <li><strong>{{ total_donors }} donor{{ total_donors|pluralize:",s" }}</strong></li>
    </ul>

    <div class="donate">
      <form
            method="post"
            class="stripe-donation"
            action-for-donation-session="{% url "fundraising:donation-session" %}"
            data-stripe-key="{{ stripe_publishable_key }}"
            data-stripe-icon="{% static 'img/dj-stripe-icon.jpg' %}"
            data-is-logged-in="{{ user.is_authenticated }}"
            data-login-url="{% url 'login' %}">
          {% csrf_token %}
        <h3>Help us make it happen:</h3>
        {{ form.interval }}
        {{ form.amount }}
        <div class="custom-donation">
          <span class="prefix">US $ (integer only)</span>
        </div>
        {{ form.captcha }}
        <input id="donate-button" type="submit" value="Donate monthly" class="cta" />
      </form>
    </div>
  </div>
  <div class="cls"></div>
  <p class="footnote">
    Your logo will be visible below if you contribute at least
    US&nbsp;${{ display_logo_amount|intcomma }}.<br>
  </p>
</div>
{% endwith %}

<hr style="margin: 40px 0" />

djangoproject/djangoproject/templates/fundraising/includes/donation_snippet.html
{% load humanize static %}

{% if donation %}
  <div class="fundraising-sidebar">
    <h2>Support Django!</h2>

    <div class="small-heart">
      <img src="{% static "img/fundraising-heart.svg" %}" alt="Support Django!" />
    </div>

    <div class="small-cta">
      <ul class="list-links-small">
        <li><a href="{% url "fundraising:index" %}">
          {{ donation.name }} donated to the Django Software Foundation to
          support Django development. Donate today!
        </a></li>
      </ul>
    </div>
  </div>
{% endif %}